<?php

/**
 * @file
 * Mailchimp Signup module. Allows creation of signup forms integrated with
 * Mailchimp.
 */

define('MAILCHIMP_SIGNUP_BLOCK', 1);
define('MAILCHIMP_SIGNUP_PAGE', 2);
define('MAILCHIMP_SIGNUP_BOTH', 3);
define('MAILCHIMP_SIGNUP_BLOCK_LABEL', 'mailchimp_signup_');

/**
 * Implements hook_menu().
 */
function mailchimp_signup_menu() {
  $items = array();

  $items['admin/config/services/mailchimp/signup'] = array(
    'title' => 'Signup Forms',
    'description' => 'Manage MailChimp Signup blocks and pages.',
    'page callback' => 'mailchimp_signup_overview_page',
    'access callback' => 'mailchimp_apikey_ready_access',
    'access arguments' => array('administer mailchimp'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/mailchimp_signup.admin.inc',
    'weight' => 10,
  );
  $items['admin/config/services/mailchimp/signup/add'] = array(
    'title' => 'Add a Signup Form',
    'description' => 'Add a new MailChimp Signup Block/Page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_signup_signup_form'),
    'access callback' => 'mailchimp_apikey_ready_access',
    'access arguments' => array('administer mailchimp'),
    'file' => 'includes/mailchimp_signup.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/services/mailchimp/signup/%mailchimp_signup/edit'] = array(
    'title' => 'Edit a signup form',
    'description' => 'Edit a Signup form.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_signup_signup_form', 5),
    'load arguments' => array(5),
    'access arguments' => array('administer mailchimp'),
    'file' => 'includes/mailchimp_signup.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/services/mailchimp/signup/%mailchimp_signup/delete'] = array(
    'title' => 'Delete Signup form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_signup_signup_delete_form', 5),
    'access arguments' => array('administer mailchimp'),
    'file' => 'includes/mailchimp_signup.admin.inc',
  );

  $signups = mailchimp_signup_load_multiple();
  foreach ($signups as $signup) {
    if (intval($signup->mode) == MAILCHIMP_SIGNUP_PAGE || intval($signup->mode) == MAILCHIMP_SIGNUP_BOTH) {
      $items[$signup->settings['path']] = array(
        'title' => $signup->title,
        'page callback' => 'mailchimp_signup_page',
        'page arguments' => array($signup->mcs_id),
        'access callback' => 'mailchimp_signup_page_access',
        'access arguments' => array('mailchimp_signup_form_' . $signup->name),
        'type' => MENU_SUGGESTED_ITEM,
      );
    }
  }
  return $items;
}

/**
 * Access callback for viewing Mailchimp subscription pages.
 */
function mailchimp_signup_page_access($permission) {
  if (user_access('mailchimp_signup_all_forms')) {
    return TRUE;
  }
  return user_access($permission);
}

/**
 * Implements hook_permission().
 */
function mailchimp_signup_permission() {
  $return = array();
  $signups = mailchimp_signup_load_multiple();
  $return['mailchimp_signup_all_forms'] = array(
    'title' => t('Access all Mailchimp Signup Forms.'),
  );
  foreach ($signups as $signup) {
    if (intval($signup->mode) == MAILCHIMP_SIGNUP_PAGE || intval($signup->mode) == MAILCHIMP_SIGNUP_BOTH) {
      $return['mailchimp_signup_form_' . $signup->name] = array(
        'title' => t('Access %title', array('%title' => $signup->title)),
        'description' => t('Allow users to access the %title Mailchimp signup page (Blocks are not impacted by this setting).', array('%title' => $signup->title)),
      );
    }
  }

  return $return;
}

/**
 * Implements hook_block_info().
 */
function mailchimp_signup_block_info() {
  $blocks = array();
  $signups = mailchimp_signup_load_multiple();
  foreach ($signups as $signup) {
    if (intval($signup->mode) == MAILCHIMP_SIGNUP_BLOCK || intval($signup->mode) == MAILCHIMP_SIGNUP_BOTH) {
      $blocks[MAILCHIMP_SIGNUP_BLOCK_LABEL . $signup->mcs_id] = array(
        'info' => t('Mailchimp Subscription Form: @name', array('@name' => $signup->label())),
        'cache' => DRUPAL_CACHE_PER_USER,
      );
    }
  }
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Provides a block for each signup configured to add a block.
 */
function mailchimp_signup_block_view($delta = '') {
  $len = strlen(MAILCHIMP_SIGNUP_BLOCK_LABEL);
  $mcs_id = substr($delta, $len);
  $signup = mailchimp_signup_load($mcs_id);
  $block = array(
    'subject' => $signup->title,
    'content' => drupal_get_form('mailchimp_signup_subscribe_form', $signup),
  );
  return $block;
}

/**
 * Wrapper around mailchimp_signup_load_multiple to load a single signup entity.
 */
function mailchimp_signup_load($signup_id) {
  $signups = mailchimp_signup_load_multiple(array($signup_id));
  if ($signups) {
    return reset($signups);
  }
  else {
    return FALSE;
  }
}

/**
 * Loads multiple signup forms.
 */
function mailchimp_signup_load_multiple($signup_ids = array(), $conditions = array(), $reset = FALSE) {
  if (empty($signup_ids)) {
    $signup_ids = FALSE;
  }

  return entity_load('mailchimp_signup', $signup_ids, $conditions, $reset);
}

/**
 * Deletes multiple signups by ID.
 *
 * @param array $signup_ids
 *   An array of signup IDs to delete.
 *
 * @return bool
 *   TRUE on success, FALSE otherwise.
 */
function mailchimp_signup_delete_multiple($signup_ids) {
  return entity_get_controller('mailchimp_signup')->delete($signup_ids);
}

/**
 * Gets an array of all Signups, keyed by the list name.
 *
 * @param string $name
 *   If set, the signup with the given name is returned.
 *
 * @return MailchimpSignup[]
 *   Depending whether $name isset, an array of signups or a single one.
 */
function mailchimp_signup_load_multiple_by_name($name = NULL) {
  $signups = entity_load_multiple_by_name('mailchimp_signup', isset($name) ? array($name) : FALSE);
  return isset($name) ? reset($signups) : $signups;
}

/**
 * Implements hook_entity_info().
 */
function mailchimp_signup_entity_info() {
  $entities = array(
    'mailchimp_signup' => array(
      'label' => t('MailChimp Signup'),
      'plural label' => t('MailChimp Signups'),
      'entity class' => 'MailchimpSignup',
      'controller class' => 'EntityAPIControllerExportable',
      'base table' => 'mailchimp_signup',
      'uri callback' => 'entity_class_uri',
      'fieldable' => FALSE,
      'exportable' => TRUE,
      'label callback' => 'entity_class_label',
      'module' => 'mailchimp_signup',
      'entity keys' => array(
        'id' => 'mcs_id',
        'name' => 'name',
      ),
      'bundles' => array(
        'mailchimp_signup' => array(
          'label' => t('MailChimp Signup'),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full'),
          'custom settings' => FALSE,
        ),
      ),
    ),
  );

  return $entities;
}

/**
 * Menu callback for Signup pages.
 */
function mailchimp_signup_page($signup_id) {
  $signup = mailchimp_signup_load($signup_id);
  return drupal_get_form('mailchimp_signup_subscribe_form', $signup);
}

/**
 * Returns a subscription form for mailchimp lists.
 *
 * If there are multiple lists, this generates a single form for all of them.
 */
function mailchimp_signup_subscribe_form($form, &$form_state, $signup) {
  $form['#attributes'] = array('class' => array('mailchimp-signup-subscribe-form'));
  $form['description'] = array(
    '#markup' => $signup->settings['description'],
  );
  $form['mailchimp_lists'] = array('#tree' => TRUE);
  $lists = mailchimp_get_lists($signup->mc_lists);
  $multiple_lists = (count($lists) != 1);

  $list = array();
  if ($multiple_lists) {
    foreach ($lists as $list) {
      // Wrap in a div:
      $wrapper_key = 'mailchimp_' . $list['web_id'];
      $form['mailchimp_lists'][$wrapper_key] = array(
        '#prefix' => '<div id="mailchimp-newsletter-' . $list['web_id'] . '" class="mailchimp-newsletter-wrapper">',
        '#suffix' => '</div>',
      );
      $form['mailchimp_lists'][$wrapper_key]['subscribe'] = array(
        '#type' => 'checkbox',
        '#title' => $list['name'],
        '#return_value' => $list['id'],
        '#default_value' => 0,
      );
      if ($signup->settings['include_interest_groups'] && isset($list['intgroups'])) {
        $form['mailchimp_lists'][$wrapper_key]['interest_groups'] = array(
          '#type' => 'fieldset',
          '#title' => t('Interest Groups for %label', array('%label' => $list['name'])),
          '#states' => array(
            'invisible' => array(
              ':input[name="mailchimp_lists[' . $wrapper_key . '][subscribe]"]' => array('checked' => FALSE),
            ),
          ),
        );
        $form['mailchimp_lists'][$wrapper_key]['interest_groups'] += mailchimp_interest_groups_form_elements($list);
      }
    }
  }
  else {
    $list = reset($lists);
    if ($signup->settings['include_interest_groups'] && isset($list['intgroups'])) {
      $form['mailchimp_lists']['#weight'] = 9;
      $form['mailchimp_lists']['interest_groups'] = mailchimp_interest_groups_form_elements($list);
    }
  }
  $form['mergevars'] = array(
    '#prefix' => '<div id="mailchimp-newsletter-' . $list['web_id'] . '-mergefields" class="mailchimp-newsletter-mergefields">',
    '#suffix' => '</div>',
    '#tree' => TRUE,
  );
  foreach ($signup->settings['mergefields'] as $tag => $mergevar) {
    if (!empty($mergevar)) {
      $form['mergevars'][$tag] = mailchimp_insert_drupal_form_tag($mergevar);
    }
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#weight' => 10,
    '#value' => $signup->settings['submit_button'],
  );

  return $form;
}

/**
 * Submit handler to add users to lists on subscription form submission.
 */
function mailchimp_signup_subscribe_form_submit($form, &$form_state) {
  $signup = reset($form_state['build_info']['args']);
  $list_details = mailchimp_get_lists($signup->mc_lists);
  $subscribe_lists = array();
  // Filter out blank fields so we don't erase values on the Mailchimp side.
  $merge_values = array_filter($form_state['values']['mergevars']);
  $email = $merge_values['EMAIL'];
  // If we only have one list we won't have checkbox values to investigate:
  if (count($signup->mc_lists) == 1) {
    $subscribe_lists[0] = array(
      'subscribe' => reset($signup->mc_lists),
      'interest_groups' => isset($form_state['values']['mailchimp_lists']['interest_groups']) ? $form_state['values']['mailchimp_lists']['interest_groups'] : NULL,
    );
  }
  else {
    // We can look at the checkbox values now:
    foreach ($form_state['values']['mailchimp_lists'] as $list) {
      if ($list['subscribe']) {
        $subscribe_lists[] = $list;
      }
    }
  }
  $successes = array();
  // Loop through the selected lists and try to subscribe:
  foreach ($subscribe_lists as $list_choices) {
    $list_id = $list_choices['subscribe'];
    $mergevars = $merge_values;
    if (isset($list_choices['interest_groups'])) {
      $mergevars['GROUPINGS'] = mailchimp_reformat_groupings($list_choices['interest_groups']);
    }
    $result = mailchimp_subscribe($list_id, $email, $mergevars, $signup->settings['doublein']);
    if (empty($result)) {
      drupal_set_message(t('There was a problem with your newsletter signup to %list.', array(
        '%list' => $list_details[$list_id]['name'],
      )), 'warning');
    }
    else {
      $successes[] = $list_details[$list_id]['name'];
    }
  }
  if (count($successes) && strlen($signup->settings['confirmation_message'])) {
    drupal_set_message($signup->settings['confirmation_message'], 'status');
  }
  if (!empty($signup->settings['destination'])) {
    $form_state['redirect'] = $signup->settings['destination'];
  }
}
