<?php

/**
 * @file
 * Mailchimp Signup module. Allows creation of signup forms integrated with
 * Mailchimp.
 */

define('MAILCHIMP_SIGNUP_BLOCK', 1);
define('MAILCHIMP_SIGNUP_PAGE', 2);
define('MAILCHIMP_SIGNUP_BOTH', 3);

/**
 * Implements hook_menu().
 */
function mailchimp_signup_menu() {
  $items = array();

  $items['admin/config/services/mailchimp/signup'] = array(
    'title' => 'Signup',
    'description' => 'Manage MailChimp Signup blocks and pages.',
    'page callback' => 'mailchimp_signup_overview_page',
    'access arguments' => array('administer mailchimp'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/mailchimp_signup.admin.inc',
    'weight' => 10,
  );
  $items['admin/config/services/mailchimp/signup/add'] = array(
    'title' => 'Add a Signup Form',
    'description' => 'Add a new MailChimp Signup Block/Page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_signup_signup_form'),
    'access arguments' => array('administer mailchimp'),
    'file' => 'includes/mailchimp_signup.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

/**
 * Loads multiple signup forms.
 */
function mailchimp_signup_load_multiple($signup_ids = array(), $conditions = array(), $reset = FALSE) {
  if (empty($signup_ids)) {
    $signup_ids = FALSE;
  }

  return entity_load('mailchimp_signup', $signup_ids, $conditions, $reset);
}

/**
 * Gets an array of all Signups, keyed by the list name.
 *
 * @string $name
 *   If set, the signup with the given name is returned.
 *
 * @return MailchimpSignup[]
 *   Depending whether $name isset, an array of signups or a single one.
 */
function mailchimp_signup_load_multiple_by_name($name = NULL) {
  $signups = entity_load_multiple_by_name('mailchimp_signup', isset($name) ? array($name) : FALSE);
  return isset($name) ? reset($signups) : $signups;
}

/**
 * Implements hook_entity_info().
 */
function mailchimp_signup_entity_info() {
  $entities = array(
    'mailchimp_signup' => array(
      'label' => t('MailChimp Signup'),
      'plural label' => t('MailChimp Signups'),
      'entity class' => 'MailchimpSignup',
      'controller class' => 'EntityAPIControllerExportable',
      'base table' => 'mailchimp_signup',
      'uri callback' => 'mailchimp_signup_uri',
      'fieldable' => FALSE,
      'exportable' => TRUE,
      'label callback' => 'entity_class_label',
      'module' => 'mailchimp_signup',
      'entity keys' => array(
        'id' => 'mcs_id',
        'name' => 'name',
      ),
      'bundles' => array(
        'mailchimp_signup' => array(
          'label' => t('MailChimp Signup'),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full'),
          'custom settings' => FALSE,
        ),
      ),
    ),
  );

  return $entities;
}
