<?php

module_load_include('inc', 'mailchimp_campaigns', 'mailchimp_campaigns.entity');

/**
 * Implements hook_permission().
 */
function mailchimp_campaigns_permission() {
  return array(
    'send mailchimp campaign' => array(
      'title' => t('Send MailChimp campaigns'),
      'description' => t('Create and send MailChimp campaigns form nodes.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mailchimp_campaigns_menu() {
  $items['admin/config/services/mailchimp/campaigns'] = array(
    'title' => 'Campaigns',
    'description' => 'Manage MailChimp Campaigns.',
    'page callback' => 'mailchimp_campaigns_overview_page',
    'access arguments' => array('administer mailchimp'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'mailchimp_campaigns.admin.inc',
    'weight' => 10
  );
  $items['admin/config/services/mailchimp/campaigns/add'] = array(
    'title' => 'Add a Campaign',
    'description' => 'Add a new MailChimp campaign.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_campaigns_campaign_form'),
    'access arguments' => array('administer mailchimp'),
    'file' => 'mailchimp_campaigns.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/services/mailchimp/campaigns/%mailchimp_campaigns/edit'] = array(
    'title' => 'Edit a list',
    'description' => 'Edit a MailChimp campaign.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_campaigns_campaign_form', 5),
    'load arguments' => array(5),
    'access arguments' => array('administer mailchimp'),
    'file' => 'mailchimp_campaigns.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/services/mailchimp/campaigns/%mailchimp_campaigns/delete'] = array(
    'title' => 'Delete list',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailchimp_campaigns_delete_list_form', 5),
    'access arguments' => array('administer mailchimp'),
    'file' => 'mailchimp_campaigns.admin.inc',
  );
  return $items;
}

/**
 * Page callback for showing a list of MC Campaign entities.
 *
 * @return array
 */
function mailchimp_campaigns_overview_page() {
  $campaigns = mailchimp_campaigns_load_multiple();

  $rows = array();
  foreach ($campaigns as $campaign) {
    $actions = array(
      l(t('View Archive'), $campaign->data['archive_url']),
      l(t('Delete'), 'admin/config/services/mailchimp/campaigns/' . $campaign->mc_campaign_id . '/delete')
    );

    $rows[] = array(
      l($campaign->data['title'],
        'admin/config/services/mailchimp/campaigns/' . $campaign->mc_campaign_id . '/edit'),
      $campaign->data['subject'],
      $campaign->data['status'],
      $campaign->data['emails_sent'],
      $campaign->data['create_time'],
      implode(' | ', $actions)
    );
  }

  return array(
    '#theme' => 'table',
    '#header' => array(
      t('Title'),
      t('Subject'),
      t('Status'),
      t('Emails Sent'),
      t('Created'),
      t('Actions')
    ),
    '#rows' => $rows
  );
}

/**
 * Implements hook_theme().
 */
function mailchimp_campaigns_theme($existing, $type, $theme, $path) {
  return array(
    'mailchimp_campaigns_node_campaigns_list' => array(
      'variables' => array('node_campaigns' => array()),
    ),
    'mailchimp_campaigns_mclinks' => array(
      'variables' => array('data' => NULL),
    ),
    'mailchimp_campaigns_actions' => array(
      'variables' => array('campaign' => NULL),
    ),
  );
}

/**
 * Create MailChimp campaign from a node.
 */
function mailchimp_campaigns_save_campaign($content, $options, $campaign_id = NULL) {
  $mcapi = mailchimp_get_api_object();
  $options += array(
    'generate_text' => TRUE,
    'tracking' => array(
      'opens' => TRUE,
      'html_clicks' => TRUE,
      'text_clicks' => TRUE,
    ),
  );

  // run our content through our text formatter
  foreach ($content as $key => $content_part) {
    $content[$key] = check_markup($content_part, variable_get('mailchimp_campaigns_format', 'mailchimp_campaign'));
  }

  // Save campaign to MailChimp. (Only regular campaigns are supported)
  $is_new = empty($campaign_id);
  if ($is_new) {
    $campaign_id = $mcapi->campaignCreate('regular', $options, $content);
  }
  else {
    // updates must be done one value at a time
    $values = $options += array('content' => $content);
    foreach ($values as $key => $value) {
      $mcapi->campaignUpdate($campaign_id, $key, $value);
    }
  }

  if ($mcapi->errorCode) {
    // Display and log error, if any.
    $message = 'MailChimp error. The campaign was not created.';
    _mailchimp_campaigns_mcapi_error_message($mcapi, $message);
  }
  else {
    drupal_set_message(t('Campaign %cid was successfully saved.',
      array('%cid' => $campaign_id)));

    // save the campaign entity
    $campaign = new stdClass;
    $campaign->mc_campaign_id = $campaign_id;
    $campaign->template = $content;
    $campaign->is_new = $is_new;
    mailchimp_campaigns_save($campaign);
  }
}

/**
 * Send MailChimp campaign.
 */
function mailchimp_campaigns_send_campaign($cid) {
  $mcapi = mailchimp_get_api_object();

  // Send campaign.
  $sent = $mcapi->campaignSendNow($cid);

  if ($mcapi->errorCode) {
    // Display and log error, if any.
    $message = 'MailChimp error. The campaign was not sent.';
    _mailchimp_campaigns_mcapi_error_message($mcapi, $message);
  }
  else {
    // Log action, and notify the user.
    $message = 'MailChimp campaign was sent.';
    drupal_set_message(t($message));
    watchdog('mailchimp_campaigns', $message);
  }
}

/**
 * Delete a MailChimp campaign and the local entity.
 */
function mailchimp_campaigns_delete_campaign($cid) {
  $mcapi = mailchimp_get_api_object();

  // Delete campaign from MailChimp
  $delete = $mcapi->campaignDelete($cid);

  if ($mcapi->errorCode) {
    // Display and log error, if any.
    $message = 'MailChimp error. The campaign was not deleted.';
    _mailchimp_campaigns_mcapi_error_message($mcapi, $message);
  }
  else {
    // Delete campaign from the database
    mailchimp_campaigns_delete($cid);
    watchdog('mailchimp_campaigns', 'MailChimp campaign %cid was deleted.', array('%cid' => $cid));
  }
}

/**
 * Return all available user templates.
 *
 * @return array().
 */
function mailchimp_campaigns_get_templates($reset = FALSE) {
  $cache = $reset ? NULL : cache_get('mailchimp_templates');
  $templates = array();
  // return cached lists
  if ($cache) {
    $templates = $cache->data;
  }
  // Query lists from the MC API and store in cache
  else {
    if ($mcapi = mailchimp_get_api_object()) {
      $response = $mcapi->templates();
      if (isset($response['user']) && count($response['user']) > 0) {
        $templates = $response['user'];
      }
    }

    cache_set('mailchimp_templates', $templates, 'cache', CACHE_TEMPORARY);
  }

  return $templates;
}

/**
 * Return all available user templates.
 *
 * @return array().
 */
function mailchimp_campaigns_get_template($tid) {
  $template = array();
  if ($mcapi = mailchimp_get_api_object()) {
    $response = $mcapi->templateInfo($tid);

    if (!empty($response)) {
      $template = $response;
    }
  }

  return $template;
}

/**
 * Set and log error messages after MailChimp API errors.
 */
function _mailchimp_campaigns_mcapi_error_message($mcapi, $message, $variables = array()) {
  $mcapiErrorMessage = 'MailChimp error code: %errorCode, MailChimp error message: %errorMessage.';
  $mcapiErrorVariables = array(
    '%errorCode' => $mcapi->errorCode,
    '%errorMessage' => $mcapi->errorMessage
  );

  $human = t($message, $variables) . ' ' . t($mcapiErrorMessage, $mcapiErrorVariables);
  drupal_set_message($human, 'error');

  $watchdog = $message . ' ' . $mcapiErrorMessage;
  $variables = $variables + $mcapiErrorVariables;
  watchdog('mailchimp_campaigns', $watchdog, $variables, WATCHDOG_ERROR);
}

/**
 * Change the relative URLs to absolute ones in the message.
 */
function mailchimp_campaigns_convert_url($text) {
  global $base_url;
  $matches = array();
  preg_match_all('/<(a|img).*?(href|src)="(.*?)"/', $text, $matches);
  foreach ($matches[3] as $key => $url) {
    if ($url[0] == '/') {
      $new_url = $base_url . $url;
      $new_match = str_replace($url, $new_url, $matches[0][$key]);
      $text = str_replace($matches[0][$key], $new_match, $text);
    }
  }

  return $text;
}

/**
 * Implements hook_filter_info().
 */
function mailchimp_campaigns_filter_info() {
  $filters['mailchimp_campaigns'] = array(
    'title' => t('MailChimp Campaign filter'),
    'description' => t('Add content and covert URLs for sending as MailChimp campaigns.'),
    'process callback' => 'mailchimp_campaigns_filter_campaign_process',
  );
  return $filters;
}

/**
 * Process callback for mailchimp_campaigns_filter_info().
 *
 * @param $text
 *   The text string to be filtered.
 * @param $filter
 *   The filter object containing settings for the given format.
 * @param $format
 *   The text format object assigned to the text to be filtered.
 * @param $langcode
 *   The language code of the text to be filtered.
 * @param $cache
 *   A Boolean indicating whether the filtered text is going to be cached in
 *   {cache_filter}.
 * @param $cache_id
 *   The ID of the filtered text in {cache_filter}, if $cache is TRUE.
 *
 * @return
 *   The filtered text.
 */
function mailchimp_campaigns_filter_campaign_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  // replace node macros with entity content
  $pattern = '/\[mailchimp_campaign\|entity_type=(\w+)\|entity_id=(\d+)\|view_mode=(\w+)\]/s';
  $text = preg_replace_callback($pattern, 'mailchimp_campaigns_process_callback', $text);

  // convert URL to absolute
  $text = mailchimp_campaigns_convert_url($text);

  return $text;
}

/**
 * preg_replace_callback() callback for mailchimp_campaigns_filter_campaign_process().
 *
 * @param array $matches
 *
 * @return string
 */
function mailchimp_campaigns_process_callback($matches = array()) {
  $content = '';
  foreach ($matches as $key => $match) {
    switch ($key) {
      case 1:
        $entity_type = $match;
        break;
      case 2:
        $entity_id = $match;
        break;
      case 3:
        $view_mode = $match;
        break;
    }
  }

  $entities = entity_load($entity_type, array($entity_id));
  if (!empty($entities)) {
    $render_array = entity_view($entity_type, $entities, $view_mode, NULL, TRUE);
    $content =  render($render_array);
  }

  return $content;
}
